# Generated by Django 3.0.3 on 2020-02-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200210_0744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
