# Generated by Django 3.0.3 on 2020-02-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_delete_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
