# Generated by Django 3.0.3 on 2020-02-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200219_1225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
